version: '3'
services:
  app:
    build: app
    container_name: app
    hostname: app
    volumes:
      - ./app/src:/code
    ports:
      - 5000:5000
    networks:
      - backend-network
      - frontend-network
      
  web:
    build: web
    container_name: web
    hostname: web
    ports:
      - 80:80
    depends_on: 
      - app
    networks:
      - frontend-network
    
networks:
  backend-network:
  frontend-network: