version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    hostname: db
    ports:
      - "33061:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./db/db-data:/var/lib/mysql
    networks:
      - backend-network
    environment:
      - MYSQL_ROOT_PASSWORD=root

  app:
    build: app
    container_name: app
    hostname: app
    volumes:
      - ./app/src:/code
    ports:
      - 5000:5000
    networks:
      - backend-network
      - frontend-network
      
  web:
    build: web
    container_name: web
    hostname: web
    ports:
      - 80:80
    depends_on: 
      - app
    networks:
      - frontend-network

volumes:
  db-data:
networks:
  backend-network:
  frontend-network: